name: snyk_sca

runs:
  using: "composite"
  steps:
    - uses: snyk/actions/setup@master

    - name: Snyk Test
      run: snyk test --json > security-reports/snyk.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
