name: trivy_fs

runs:
  using: "composite"
  steps:
    - name: Trivy (Filesystem)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: fs
        output: security-reports/trivy-fs.json
