name: checkov_iac

runs:
  using: "composite"
  steps:
    - name: Checkov IaC Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: json
        output_file_path: security-reports/checkov.json
