name: deploy_vm2

runs:
  using: "composite"
  steps:
    - name: SSH to Bastion and Deploy
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/playbooks/deploy_app.yml \
          --extra-vars "image_tag=${{ github.sha }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
