---
- name: Install Docker & Docker Compose
  ansible.builtin.dnf:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable & start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Create DB directory
  ansible.builtin.file:
    path: /opt/db
    state: directory

- name: Deploy DB docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/db/docker-compose.yml

- name: Bring up DB stack
  ansible.builtin.shell: |
    cd /opt/db
    docker compose up -d
  args:
    executable: /bin/bash
