services:
  vuln-bank:
    image: ${IMAGE_WITH_TAG}
    container_name: vuln-bank-app
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      DB_NAME: vulnerable_bank
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}

      DB_CONNECT_RETRIES: 20
      DB_CONNECT_DELAY: 3

    volumes:
      - uploads:/app/static/uploads:rw

    read_only: true

    tmpfs:
      - /tmp
      - /var/tmp

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://127.0.0.1:5000/healthz', timeout=2)"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  uploads: