---
project_name: vuln-bank
dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') | default('your-dockerhub', true) }}"
dockerhub_repo: "{{ dockerhub_username }}/vuln-bank"

# versi image terakhir dari pipeline
vuln_bank_image_tag: "latest"  # bisa di-overwrite dari extra-vars
vuln_bank_image: "{{ dockerhub_repo }}:{{ vuln_bank_image_tag }}"

# OpenSCAP & CIS
cis_profile: "xccdf_org.ssgproject.content_profile_cis_server_l1"
cis_min_score: 80

# Lokasi compose file di VM
vm2_compose_path: /opt/vuln-app/docker-compose.vm2-app.yml
vm3_compose_path: /opt/vuln-db/docker-compose.vm3-db.yml

# ENV App (boleh di-override dari vault / secret)
db_name: vulnerable_bank
db_user: postgres
db_password: postgres
db_host_vm3: "192.168.107.130"
db_port: 5432
