---
- name: Create postgres directory
  file:
    path: /opt/vuln-bank-db
    state: directory
    owner: db
    group: db
    mode: '0750'

- name: Add db user to docker group
  user:
    name: db
    groups: docker
    append: true
