---
# Docker image dari CI pipeline
app_image: "{{ FULL_IMAGE | default('docker.io/vuln-bank:latest') }}"

# Directory tempat Docker Compose tinggal
app_compose_dir: "/opt/vuln-bank"
db_compose_dir: "/opt/vuln-bank-db"

# Fields yang akan digenerate dari VULN_ENV_FILE
vuln_env_file: ""

# Optional override (if needed)
db_user: "{{ lookup('env','DB_USER') | default('postgres') }}"
db_password: "{{ lookup('env','DB_PASSWORD') | default('postgres') }}"
flask_secret_key: "{{ lookup('env','FLASK_SECRET_KEY') | default('vulnsecret') }}"
