version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vuln-bank-db

    user: "999:999"   # postgres user (Podman-safe)

    environment:
      POSTGRES_DB: vulnerable_bank
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pg_data:/var/lib/postgresql/data

    restart: unless-stopped

    security_opt:
      - label=disable   # SELinux-safe for Podman

    ports:
      - "5432:5432"

volumes:
  pg_data:
    driver: local