apiVersion: v1
kind: Namespace
metadata:
  name: vuln-bank-db
  labels:
    name: vuln-bank-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vulnbank-db
  namespace: vuln-bank-db
spec:
  serviceName: vulnbank-db
  replicas: 1
  selector:
    matchLabels:
      app: vulnbank-db
  template:
    metadata:
      labels:
        app: vulnbank-db
    spec:
      nodeSelector:
        node-role.kubernetes.io/db: "true"
      containers:
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: vulnbank-db-credentials
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
              cpu: "2000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vulnbank-db
  namespace: vuln-bank-db
spec:
  type: ClusterIP
  selector:
    app: vulnbank-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: vulnbank-db
  namespace: vuln-bank-db
spec:
  type: ClusterIP
  selector:
    app: vulnbank-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-default-deny
  namespace: vuln-bank-db
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-db
  namespace: vuln-bank-db
spec:
  podSelector:
    matchLabels:
      app: vulnbank-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: vuln-bank-app
      ports:
        - protocol: TCP
          port: 5432
