---
- name: Install Docker & Docker Compose
  ansible.builtin.dnf:
    name:
      - docker
      - docker-compose
    state: present

- name: Enable & start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Create SonarQube directory
  ansible.builtin.file:
    path: /opt/sonarqube
    state: directory

- name: Deploy SonarQube docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/sonarqube/docker-compose.yml

- name: Bring up SonarQube stack
  ansible.builtin.shell: |
    cd /opt/sonarqube
    docker compose up -d
  args:
    executable: /bin/bash
