---
- name: Add Docker repo
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  notify: restart docker

- name: Install Docker Engine + compose plugin
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker service running
  service:
    name: docker
    state: started
    enabled: true

- name: Add ansible_user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset SSH connection to load new group
  meta: reset_connection
