name: Reusable - DAST ZAP

on:
  workflow_call:
    inputs:
      image_ref:
        type: string
        required: true
    outputs:
      alerts:
        value: ${{ jobs.zap.outputs.alerts }}

jobs:
  zap:
    runs-on: ubuntu-latest
    outputs:
      alerts: ${{ steps.extract.outputs.alerts }}

    steps:
      - uses: actions/checkout@v4

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name app ${{ inputs.image_ref }}
          sleep 10

      - name: Run ZAP Baseline
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network host \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:5000 \
            -J zap.json \
            -r zap.html

      - id: extract
        run: |
          CNT=$(jq '.site[].alerts | length' zap.json)
          echo "alerts=$CNT" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap.*
